source: ./src
destination: ./build

gems:
- jekyll-compass

markdown: redcarpet

redcarpet:
  extensions:
  - footnotes
  - highlight
  - underline
  - smart
  - space_after_headers
  - strikethrough

title: Matthew Scharley
domain: matt.scharley.me
author:
  name: Matthew Scharley
  email: matt.scharley@gmail.com
disqus:
  shortname: msme
sitemap:
  url: http://matt.scharley.me
  filename: sitemap.xml

timezone: "Australia/Melbourne"
encoding: "UTF-8"
