pygments: true
exclude:
- LICENSE.md
- README.md
- Rakefile
- CNAME
- Gemfile
- Gemfile.lock
- matt.scharley.me.iml
- atlassian-ide-plugin.xml
- s3_website.yml
- bower.json

gems:
- jekyll-compass

markdown: redcarpet

redcarpet:
  extensions:
  - footnotes
  - highlight
  - underline
  - space_after_headers
  - strikethrough

title: Matthew Scharley
domain: matt.scharley.me
author:
  name: Matthew Scharley
  email: matt.scharley@gmail.com
disqus:
  shortname: msme
sitemap:
  url: http://matt.scharley.me
  filename: sitemap.xml

timezone: "Australia/Melbourne"
encoding: "UTF-8"
