pygments: true
exclude:
- LICENSE.md
- README.md
- Rakefile
- CNAME
- Guardfile
- Gemfile
- Gemfile.lock
- matt.scharley.me.iml
- atlassian-ide-plugin.xml
- s3_website.yml

title: Matthew Scharley
domain: matt.scharley.me
author:
  name: Matthew Scharley
  email: matt.scharley@gmail.com
disqus:
  shortname: msme
sitemap:
  url: http://matt.scharley.me
  filename: sitemap.xml
